#!/usr/bin/env python
# Setup of the docker image for jobe. Docker must already be installed.
# Designed to avoid the need for a docker python library
# Designed and tested on centos/Red Hat 7 only

import subprocess
import os
from pprint import pprint
from shutil import copyfile

def build_container():

	# Get runguard and put it in this folder
        copyfile('../runguard/runguard', './runguard')	
	os.chmod('./runguard',0700)
	# build the container
	subprocess.call(['docker', 'build', '.'])

def tag_container():
	imageid = subprocess.check_output(['docker', 'images', '--filter=dangling=true', '--format', '{{.ID}}'])
	subprocess.call(['docker', 'tag', imageid.rstrip(), 'local/jobe-centos'])

def update_apache_env():
	with open("/etc/sysconfig/httpd", "a") as f:
		f.write("DOCKER_HOST=unix:///var/run/docker.sock\n")
	subprocess.call(['systemctl', 'restart', 'httpd'])
	
	

def main():
	build_container()
	tag_container()
	update_apache_env()

main()
